#!/bin/bash
workspaceDir=$(pwd)/..
tmpFile=/tmp/javaFiles.txt

srcDir=$workspaceDir/src
binDir=$workspaceDir/bin

outputJar=$workspaceDir/3DRendererDemo.jar

if ! [ -d $binDir ]; then
    echo "Recreating directory tree"
    mkdir $binDir
fi

echo "Locating java files"
find $srcDir -name *.java > $tmpFile

echo "Compiling java files"
javac -cp $workspaceDir/lib/MyLibrary.jar:$binDir -d $binDir @$tmpFile

echo "Extracting libraries"
cd $binDir
jar -xf $workspaceDir/lib/MyLibrary.jar sk CmdUtils32.dll CmdUtils64.dll

echo "Creating jar file"
jar -cfe $workspaceDir/3DRendererDemo.jar sk.pa3kc.Program -C $binDir .
