#!/bin/bash
workspaceDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"/..

binDir=$workspaceDir/bin

tmpFile=/tmp/javaFiles.txt
outputJar=$workspaceDir/3DRendererDemo.jar

if [ -d $binDir ]; then
    echo "Clearing bin directory"
    rm --recursive --force $binDir/*
fi
if [ -f $tmpFile ]; then
    echo "Removing tmp files"
    rm --force $tmpFile
fi
if [ -f $outputJar ]; then
    echo "Removing outputed jar"
    rm --force $outputJar
fi
